services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: nextjs-cashback:latest
    environment:
      - NODE_ENV=production
    ports:
      - "3000:3000"
    restart: unless-stopped
    healthcheck:
      test:
        [
          "CMD-SHELL",
          'node -e "require(''http'').get(''http://127.0.0.1:3000'', res => { if (res.statusCode >= 200 && res.statusCode < 400) process.exit(0); else process.exit(1); }).on(''error'', () => process.exit(1))"',
        ]
      interval: 30s
      timeout: 10s
      retries: 5
